### ISSUE TITLE
new libs c-header-to-bqn-ffi and bqn-socket 

### ISSUE THREAD

**Issue by Brian-ED** [pellertson/awesome-bqn#2]
link: https://github.com/Brian-ED/c-header-to-bqn-ffi/ 
desc: made for parsing c header files into `•ffi` files.

https://github.com/Brian-ED/bqn-socket/
desc: library for making it easier to use sockets

**Comment by pellertson** [comment]
Thanks @Brian-ED! I've added the links to the list.  I'm going to work on improving the list in the morning.
